name: CI-tests-unitaires

on:
  push:
    branches:
      - main
      - feature-*

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lancer les tests unitaires
      run: |
        python -m unittest discover tests/unit
